# 数据探索

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from math import *
%matplotlib inline

### 1.读入商品数据

In [2]:
File = './data/JData_Product.csv'

In [3]:
df = pd.read_csv(File,encoding='gbk')
print(type(df))
print(df.head())

<class 'pandas.core.frame.DataFrame'>
   sku_id  a1  a2  a3  cate  brand
0      10   3   1   1     8    489
1  100002   3   2   2     8    489
2  100003   1  -1  -1     8     30
3  100006   1   2   1     8    545
4   10001  -1   1   2     8    244


### 2.商品数据探索

In [4]:
df.describe()

sku_id            a1            a2            a3     cate  \
count   24187.000000  24187.000000  24187.000000  24187.000000  24187.0   
mean    85398.737421      2.176996      0.938975      1.179766      8.0   
std     49238.799482      1.176116      0.969517      1.045883      0.0   
min         6.000000     -1.000000     -1.000000     -1.000000      8.0   
25%     42476.000000      1.000000      1.000000      1.000000      8.0   
50%     85616.000000      3.000000      1.000000      1.000000      8.0   
75%    127774.000000      3.000000      2.000000      2.000000      8.0   
max    171224.000000      3.000000      2.000000      2.000000      8.0   

              brand  
count  24187.000000  
mean     435.864307  
std      225.749190  
min        3.000000  
25%      214.000000  
50%      489.000000  
75%      571.000000  
max      922.000000

In [5]:
# 查看数据条数
len(df)

24187

In [6]:
# 查看属性非空条数
df['sku_id'].count()

24187

In [7]:
# 查看属性非空条数
df['a1'].count()

24187

In [8]:
# 查看属性非空条数
df['a2'].count()

24187

In [9]:
# 查看属性非空条数
df['a3'].count()

24187

In [10]:
# 查看属性非空条数
df['cate'].count()

24187

In [11]:
# 查看属性非空条数
df['brand'].count()

24187

### 3.数据清洗

### 4.查看属性的取值分布情况 

In [12]:
#查看属性的值
df['a1'].unique()

array([ 3,  1, -1,  2])

In [13]:
#查看每一个属性取值的数据条数
df['a1'].value_counts()

 3    14144
 1     4760
 2     3582
-1     1701
Name: a1, dtype: int64

In [14]:
#查看属性的值
df['a2'].unique()

array([ 1,  2, -1])

In [15]:
#查看每一个属性取值的数据条数
df['a2'].value_counts()

 1    13513
 2     6624
-1     4050
Name: a2, dtype: int64

In [16]:
df['a3'].unique()

array([ 1,  2, -1])

In [17]:
#查看每一个属性取值的数据条数
df['a3'].value_counts()

 2    11978
 1     8394
-1     3815
Name: a3, dtype: int64

In [18]:
df['cate'].unique()

array([8])

In [19]:
df['brand'].unique()

array([489,  30, 545, 244, 214, 124, 306, 403, 174, 812, 635, 885, 658,
       321, 790, 875, 766, 800, 693, 623, 571, 556, 801, 101, 596, 605,
       562, 427, 673, 200,  91, 355, 375, 655, 916,  70, 804, 561, 622,
       263, 900, 159, 677, 484,  88,  14,  76, 665, 674, 116,  25, 324,
       318,  90, 328, 541,  83,  24, 837, 291, 717, 127, 249,  51, 857,
       383, 370,   3, 404, 599, 209, 453, 197, 594, 922, 855, 574, 772,
       211, 331,  48, 515, 225, 180, 752, 283, 438, 907, 336, 905,  13,
       299, 759,  49, 479, 354, 285, 739, 227, 554, 871, 499])

In [20]:
df['brand'].value_counts()

489    6637
214    6444
623    1101
812    1061
800    1015
545     945
124     932
306     795
30      659
885     601
403     517
693     372
658     368
766     254
571     235
635     199
562     134
244     114
655     102
622      97
801      94
321      82
790      81
677      77
200      72
427      67
674      53
174      50
857      49
596      48
       ... 
574       4
665       4
116       4
291       3
197       3
383       3
180       2
739       2
227       2
907       2
759       2
453       2
324       2
336       1
285       1
479       1
49        1
752       1
13        1
772       1
331       1
299       1
354       1
922       1
554       1
905       1
871       1
855       1
499       1
438       1
Name: brand, dtype: int64

### 5.特征处理 

In [ ]:
# 对sex做离散化,把三个取值,展开成三列,对应的位置为1,其余为0
# 男(0) -> sex_male
# 女(1) -> sex_female
# 保密(2) -> sex_unknow
# 初始化
user_df['sex_male'] = 0.0
user_df['sex_female'] = 0.0
user_df['sex_unknow'] = 0.0

In [ ]:
user_df.head()

In [ ]:
# 离散化
user_df.loc[user_df['sex'] == 0.0,'sex_male']=1
user_df.loc[user_df['sex'] == 1.0,'sex_female']=1
user_df.loc[user_df['sex'] == 2.0,'sex_unknow']=1

In [ ]:
user_df.head()

In [ ]:
# 对age做变换
# 初始化
user_df['age_15'] = 0.0
user_df['age_25'] = 0.0
user_df['age_35'] = 0.0
user_df['age_45'] = 0.0
user_df['age_55'] = 0.0
user_df['age_56'] = 0.0
user_df['age_unknow'] = 0.0

# 数据变换
user_df.loc[user_df['age'] == '15岁以下','age_15']=1
user_df.loc[user_df['age'] == '16-25岁','age_25']=1
user_df.loc[user_df['age'] == '26-35岁','age_35']=1
user_df.loc[user_df['age'] == '36-45岁','age_45']=1
user_df.loc[user_df['age'] == '46-55岁','age_55']=1
user_df.loc[user_df['age'] == '56岁以上','age_56']=1
user_df.loc[user_df['age'] == '-1','age_unknow']=1

In [ ]:
user_df.head()

In [ ]:
# 计算用户注册时间,同时做离散化处理
# 使用datetime
# from datetime import datetime
# datetime.strptime(user_df['user_reg_tm'][0],'%Y-%m-%d')

In [ ]:
# 使用parse
# from dateutil.parser import parse
# parse(user_df['user_reg_tm'][0])

In [ ]:
# 使用.to_datetime
user_df['user_reg_tm']=pd.to_datetime(user_df['user_reg_tm'])

In [ ]:
# 计算注册时间
user_df['time_delta']= pd.Series([x.days for x in (user_df['user_reg_tm'] - datetime(2016,4,15))])

In [ ]:
# 查看注册日期在2016/4/15之后的用户的数量
len(user_df[user_df['time_delta']>0])

In [ ]:
# 题目要求预测 2016-04-16到2016-04-20用户是否下单P中的商品
# 因此注册日期在2016/4/15的用户数据不符合要求,丢弃这部分数据
user_df=user_df[user_df['time_delta']<0]

In [ ]:
# 查看注册日期在2016/4/15之后的用户的数量
len(user_df[user_df['time_delta']>0])

In [ ]:
# 注册日期是连续变量,做归一化处理
from sklearn import preprocessing

user_df['time_delta_z']=pd.Series(preprocessing.scale(user_df['time_delta'].apply(abs).values))

In [ ]:
user_df.head()

In [ ]:
# 处理好的数据写入到文件
# 丢弃处理之前的属性列
colDrop = ['age','sex', 'user_reg_tm']
user_df_sel =user_df.drop(colDrop,axis=1).copy()

In [ ]:
user_df_sel.head()

In [ ]:
user_df_sel.to_csv('../user_df_sel.csv',index=False)